# Generated by Django 5.1.1 on 2024-10-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('maturity_rate', models.CharField(blank=True, choices=[('L', 'Livre'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=2, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movies/')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='actors.actor')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='genres.genre')),
            ],
        ),
    ]
