# Generated by Django 5.1.1 on 2024-09-23 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity_rate', models.CharField(blank=True, choices=[('L', 'Livre'), ('10', '10 anos'), ('12', '12 anos'), ('14', '14 anos'), ('16', '16 anos'), ('18', '18 anos')], max_length=2, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movies')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='genres.genre')),
            ],
        ),
    ]
